- apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
